main: mazaicrafty\nopfly\Main
name: NopFly
version: 1.1.3
api:
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
author: MazaiCrafty
website: https://github.com/MazaiCrafty
load: POSTWORLD
description: ""
commands:
  nopfly:
    description: "NoOP NoFly <true/false/query/lang/punishment/setmethod>"
    usage: "/nopfly <on/true || off/false || query/config || lang (jpn/eng) || punishment (kick/ban)|| setmethod (form)>"
    permission: nopfly
